server:
  port: 8080
spring:
  application.name: whiskyup
cloud:
  aws:
    stack:
      auto: false
    dynamodb:
      table:
        whisky-base: WhiskyBase
        user: User
jwt:
  secret:
    mock: mockSecretJwtKeyUsedWithHs512MustHaveSizeEqualOrGraterThan512BitsmockSecretJwtKeyUsedWithHs512MustHaveSizeEqualOrGraterThan512Bits
    key: ${JWT_SECRET_KEY:${jwt.secret.mock}}

---

spring:
  config:
    activate:
      on-profile: local
cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-central-1
    end-point:
      uri: http://localstack:4566