server:
  port: 80
spring:
  application.name: whiskyup
jwt:
  secret:
    key: ${JWT_SECRET_KEY:mockSecretJwtKeyUsedWithHs512MustHaveSizeEqualOrGraterThan512BitsmockSecretJwtKeyUsedWithHs512MustHaveSizeEqualOrGraterThan512Bits}
cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: eu-central-1
    dynamodb:
      table:
        whiskyup: WhiskyUp
    sqs:
      queue:
        new-url: new-url
        whisky: whisky
---
spring:
  config:
    activate:
      on-profile: test
cloud:
  aws:
    sqs:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: local
cloud:
  aws:
    endpoint: http://localstack:4566