openapi: 3.0.3
info:
  title: Whisky Up API
  version: 1.0.0
paths:
  /urls:
    get:
      summary: Get whiskies urls
      operationId: getWhiskiesUrls
      parameters:
        - name: pageCursor
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrlsFindResult'
  /brands:
    get:
      summary: Get brands
      operationId: getBrands
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /price-ranges:
    get:
      summary: Get price rangesg
      operationId: getPriceRanges
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /whiskies:
    get:
      summary: Get whiskies
      operationId: getWhiskies
      parameters:
        - name: pageCursor
          in: query
          required: false
          schema:
            type: string
        - name: filter
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/FilterType"
        - name: value
          in: query
          required: false
          schema:
            type: string
        - name: sort
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/SortType"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WhiskiesFindResult'
  /user:
    post:
      summary: Add user
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /user/{id}/whiskies:
    get:
      summary: Get user whiskies
      operationId: getUserWhiskies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: pageCursor
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWhiskiesFindResult'
  /user/{id}/whisky:
    post:
      summary: Add user whisky
      operationId: addUserWhisky
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWhisky'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWhisky'
components:
  schemas:
    WhiskiesFindResult:
      type: object
      properties:
        pageCursor:
          type: string
        results:
          type: array
          items:
            $ref: "#/components/schemas/Whisky"
    UserWhiskiesFindResult:
      type: object
      properties:
        pageCursor:
          type: string
        results:
          type: array
          items:
            $ref: "#/components/schemas/UserWhisky"
    UrlsFindResult:
      type: object
      properties:
        pageCursor:
          type: string
        results:
          type: array
          items:
            type: string
    Whisky:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        addedDate:
          type: string
        name:
          type: string
        thumbnailUrl:
          type: string
        category:
          type: string
        distillery:
          type: string
        bottler:
          type: string
        bottlingSeries:
          type: string
        bottled:
          type: string
        brand:
          type: string
        vintage:
          type: integer
          format: int32
        statedAge:
          type: integer
          format: int32
        strength:
          type: number
          format: double
        size:
          type: integer
          format: int32
        sizeUnit:
          type: string
        rating:
          type: number
          format: double
        userRating:
          type: number
          format: double
        amountOfRatings:
          type: integer
          format: int32
        price:
          type: number
          format: double
        currency:
          type: string
        tags:
          type: array
          items:
            type: string
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
        distillery:
          type: string
    UserWhisky:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        thumbnailUrl:
          type: string
        category:
          type: string
        bottler:
          type: string
        bottlingSeries:
          type: string
        bottled:
          type: string
        vintage:
          type: integer
          format: int32
        statedAge:
          type: integer
          format: int32
        strength:
          type: number
          format: double
        size:
          type: integer
          format: int32
        sizeUnit:
          type: string
        rating:
          type: number
          format: double
        price:
          type: number
          format: double
        currency:
          type: string
        tags:
          type: array
          items:
            type: string
    FilterType:
      type: string
      enum:
        - priceRange
        - brand
    SortType:
      type: string
      enum:
        - asc
        - desc