version: '3.7'
services:
  backend:
    container_name: backend
    image: whiskyup/backend:new
    ports:
      - '8080:80'
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - INIT_MODE=true
  crawler:
    container_name: crawler
    image: whiskyup/crawler
    depends_on:
      - backend
    environment:
      - RUN_PROFILE=local
      - ENDPOINT_URL=http://localstack:4566
      - KNOWN_WHISKIES_URL=http://backend:80/urls
      - MAX_NUMBER_OF_PAGES_TO_CRAWL_OVER=1000
      - URLS_TO_BE_SCRAPPED_QUEUE=http://localstack:4566/000000000000/new-url
      - URLS_TO_BE_DELETED_QUEUE=http://localstack:4566/000000000000/whisky
  scraper:
    container_name: scraper
    image: whiskyup/scraper
    environment:
      - RUN_PROFILE=local
      - ENDPOINT_URL=http://localstack:4566
      - URLS_TO_BE_SCRAPPED_QUEUE=http://localstack:4566/000000000000/new-url
      - WHISKIES_TO_BE_ADDED_QUEUE=http://localstack:4566/000000000000/whisky
      - AWS_ACCOUNT_ID=000000000000
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=mock
      - AWS_SECRET_ACCESS_KEY=mock
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs,dynamodb,iam
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'