version: '3.7'
services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=local
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs,dynamodb,iam
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
      - LAMBDA_DOCKER_NETWORK=application
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'